### PR TITLE
feat: Change data.wynntils link to Wynncraft item guide

### PR DESCRIPTION
**Pull request by ShadowCat117**
See https://github.com/Wynntils/Wynntils/pull/3023

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Actually, can you test if removing a key makes the mod crash? I really don't think so, I think it behaves properly since my last changes. @ShadowCat117

**Comment by ShadowCat117** [comment]
No crash from current release but it hasn't actually loaded the urls file, the pr to fix it works fine though

**Comment by ShadowCat117** [comment]
```
[18:28:53] [Render thread/WARN] (wynntils) Missing URL in urls.json: LINK_WYNNDATA_ITEM_LOOKUP
[18:28:54] [ForkJoinPool.commonPool-worker-1/WARN] (wynntils) Missing URL in urls.json: LINK_WYNNDATA_ITEM_LOOKUP
[18:28:54] [ForkJoinPool.commonPool-worker-1/ERROR] (wynntils) Critical error while updating URL list from online source
 java.lang.IllegalStateException: Remote URL list has a lower version than the local cache. This should not happen.
```

**Comment by kristofbolyai** [comment]
In fact that is an issue. You know the drill, add back the old key, and create a new one also.

**Comment by ShadowCat117** [comment]
Thought bumping the version wouldn't make the mod download it until the bundled one was the same version :/

**Comment by kristofbolyai** [comment]
Not how it works. In fact, the mod prefers the higher version. It might actually be fine if you didn't bump the version, so it merged the bundled and online ones.

**Pull request merged**
