### PR TITLE
feat: Automatically extract services.json from v3 map API

### PR DESCRIPTION
**Pull request by kristofbolyai**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Y levels are a bit off, usually by 2-4 blocks, which means there is no pattern for correcting it... I would still go with this data, because on the map it is accurate, and when "tracked", it is just the Y levels being in ground.

**Comment by magicus** [comment]
I'm kind of confused. Didn't we do this before?

**Comment by kristofbolyai** [comment]
> I'm kind of confused. Didn't we do this before? 

I migrated everything to v3, but I didn't know this was available on v3, so I left it out.

**Comment by magicus** [comment]
Hm, there is `update-wynn-locations.sh` in Data-Storage, but it was apparently not copied here.

**Comment by magicus** [comment]
And it used a slightly different method. Anyway, this was great!

**Pull request merged**
