### PR TITLE
chore: [auto-generated] Update identification keys from upstream

### PR DESCRIPTION
**Pull request by WynntilsBot**
Upstream Wynncraft API has been updated with new identification keys.

Please verify that the ids are correctly incremented, old ids are not removed, and the new ids are incrementing from the last id. 
If the ids reach 255, please reach out to the Artemis team to discuss how to handle this. Most likely the gear chat encoding needs to have a new version created.

This PR has been automatically generated.

### CODE REVIEW

**Comment by magicus** [comment]
I guess this is sane. @kristofbolyai?

**Comment by kristofbolyai** [comment]
> I guess this is sane. @kristofbolyai?

I am not sure this stat even exists, it's one of the "flickering" ones.

**Comment by magicus** [comment]
Ah, I see.

**Comment by kristofbolyai** [comment]
> Ah, I see.

I plan to add some way to address this without flickering PRs, however, it may take a while, since I have much less free time for OSS atm.

**Comment by magicus** [comment]
The flickering is actually a bug on the part of Wynncraft. Do you know if they are aware of it, and if they are working on it? Basically what it means is that they sometimes provide incorrect data from their API.

**Comment by kristofbolyai** [comment]
> The flickering is actually a bug on the part of Wynncraft. Do you know if they are aware of it, and if they are working on it? Basically what it means is that they sometimes provide incorrect data from their API.

I think they are semi-aware. For example, for gear items, it's a known issue that some items are "duplicated" internally, and whenever the API re-caches (and does a full recalculation, items can change). As for other routes, I have not reported them yet.

**Pull request closed without merging**
