### PR TITLE
chore: bump version number on md5sum change

### PR DESCRIPTION
**Pull request by kristofbolyai**
I believe this version bumping is not strictly necessary, but we might as well use it to indicate changes.

### CODE REVIEW

**Comment by magicus** [comment]
Hm, what is the rationale for doing that? That will make the version number speed away like crazy.

As I recall it, the version number was introduced to be able to watch for *backwards incompatible* changes; not changes in general. A new md5 is definitely not backwards incompatible.

I am genuinely worried that doing this will make the version number lose it's original purpose, and that this will force us to introduce a new "real version number" field instead...

**Comment by kristofbolyai** [comment]
I don't think that is the case. The mod uses the highest versioned urls.json it has. (How it handles the same version, I have no idea about, it either ignores the remote ones, prefers the remote one, or is a loading race and undefined.

We already have trouble whenever we need to **remove** a field from urls.json, as older versions don't really handle that, and they rather crash easily. Same with data, we can't remove files for such long times.

**Comment by kristofbolyai** [comment]
What we ideally would need is two numbers, a version and a revision. A mod can only handle the version it has been shipped with, but can handle the latest revision. However that would mean, we have to do versioned releases of Stable-Storage and download the files from there. Which would not be so problematic if it was not so many files, that we would need to zip them in the release, and the mod would have to decompress it..

**Comment by magicus** [comment]
The original problem was that we could inadvertently downgrade the json to a version without a newly added field. So we made sure we shipped an updated urls.json with the mod, when we had an update requiring a new field for instance, and then it would never be downgraded to one without that field.

I agree that our story does not really support removing fields from urls.json. It's a bit sad, but I don't know how we could ever handle that. Maybe we can mark urls as deprecated, and if Wynntils finds a deprecated url and tries to access it, it should warn the user + send a Telemetry report to Athena (if enabled). That way we can try to keep track of if deprecated URLs are actually used.

**Comment by magicus** [comment]
Yes, what you describe is probably the "correct" way to do this. Kind of like having a major (breaking) and minor (non-breaking) versioning of the format.

But that will easily lead to an explosion in the support matrix. I really hope we can find a way to avoid doing that. Even just keeping old URLs around forever seem better to me.

**Comment by kristofbolyai** [comment]
I'll check what Artemis is doing with urls, and deploy a patch to favor Static-Storage urls, or try to do some kind of conflict resolution, although I don't think we could do much in that regard.

**Comment by magicus** [comment]
I'm starting to think we maybe should get rid of the separate download of urls.json, and just keep it bundled with the mod. I know I met fierce resistance from @DevScyu and @HeyZeer0 last time I suggested this, since they had bad experience of some service going down, and then all versions of the mod went useless, and all they wanted to do was to replace a URL in all instances of the mods, to another place where the service could be gotten from.

However, I think this is a very special case to protect ourselves from, and the cost of doing this is rather high. We could hard-code the actual URLs with each release of the mod, but still keep the option of actually being able to update the content of the data files.

That way we would never need to worry about a conflict like gear.json/gear_advanced.json, since every specific instance of the mod would know what file it requires to work.

**Pull request merged**
