### PR TITLE
feat: Use beta api for players, guilds, leaderboards and territories

### PR DESCRIPTION
**Pull request by ShadowCat117**

### CODE REVIEW

**Comment by kristofbolyai** [comment]
Did you verify these work? Also, perhaps this should be updated on Static-Storage, then just merged in here.

**Comment by kristofbolyai** [comment]
I'd assume we don't crash/spams because of the territory locations. If we do, I'd rather see that fixed, as logging errors (aka disk IO) can easily cause performance issues.

**Comment by kristofbolyai** [comment]
If you verified that, feel free to merge this.

**Review by kristofbolyai — APPROVED** [review]

**Comment by ShadowCat117** [comment]
It'll log `Failure in net manager [handleJsonObject], processing DL:dataWynncraftTerritoryListV3: Cannot invoke "com.google.gson.JsonArray.get(int)" because "start" is null` every time it makes the call and no territory info is loaded due to that.

Could pr a fix but would need to either set a better default location for the territories as currently they are

```
int startX = Integer.MAX_VALUE - 1;
int startZ = Integer.MAX_VALUE - 1;
int endX = Integer.MAX_VALUE;
int endZ = Integer.MAX_VALUE;
```

and they'll crash the guild map due to BoundingBox assertion `assert x1 < x2 && z1 < z2;`

**Comment by kristofbolyai** [comment]
> It'll log `Failure in net manager [handleJsonObject], processing DL:dataWynncraftTerritoryListV3: Cannot invoke "com.google.gson.JsonArray.get(int)" because "start" is null` every time it makes the call and no territory info is loaded due to that.
> 
> 
> 
> Could pr a fix but would need to set a better default location for the territories as currently they are
> 
> 
> 
> ```
> 
> int startX = Integer.MAX_VALUE - 1;
> 
> int startZ = Integer.MAX_VALUE - 1;
> 
> int endX = Integer.MAX_VALUE;
> 
> int endZ = Integer.MAX_VALUE;
> 
> ```
> 
> 
> 
> and they'll crash the guild map due to BoundingBox assertion `assert x1 < x2 && z1 < z2;`

Ouch! Time to bump the urls version, and not merge this PR in Static Storage, only in Wynntils#main.

**Comment by ShadowCat117** [comment]
I think the easiest solution for no location territories is to just ignore them, as without a location they're basically useless. Can't tell if you're inside it and nowhere to render it on the map

**Pull request closed without merging**
