### PR TITLE
chore: [auto-generated] Update gear data from upstream

### PR DESCRIPTION
**Pull request by WynntilsBot**
Upstream Wynncraft API has been updated with new gear data.

If new field types are introduced, please to not merge this PR until the Wynntils mod has been updated to support these changes.

This PR has been automatically generated.

### CODE REVIEW

**Comment by kristofbolyai** [comment]
This PR was opened because of https://github.com/Wynntils/Static-Storage/commit/939f8b016c9be5ff8fe9ad6d44d03e3f47599567. Do not merge this. 

The new item obtain type, "miniboss", was not known by Artemis, and due to an overlook, instead of failing peacefully (and not parsing item obtain info for that single item), crashes the whole gear deserialization process, making item-related features not work. 

`Artemis v1.1.5` contains a fix for this issue, however, we have to give it significant time to get people to update, as it is a stable version.

**Comment by magicus** [comment]
> Artemis v1.1.5 contains a fix for this issue, however, we have to give it significant time to get people to update, as it is a stable version.

@kristofbolyai Maybe this has been enough time?

**Comment by kristofbolyai** [comment]
> > Artemis v1.1.5 contains a fix for this issue, however, we have to give it significant time to get people to update, as it is a stable version.
> 
> @kristofbolyai Maybe this has been enough time?

Wynncraft 2.1 is releasing soon(-ish). I might as well wait until that, because it definitely breaks the game.

**Comment by magicus** [comment]
> Artemis v1.1.5 contains a fix for this issue, however, we have to give it significant time to get people to update, as it is a stable version.

I guess that time is now?

**Comment by magicus** [comment]
So that is why all updates are broken.

Anyway, my comment was about the "miniboss" change. With release 2.0 of Wynntils, I believe enough time has passed.

**Comment by kristofbolyai** [comment]
Indeed, that’ll be resolved now.

**Pull request closed without merging**
